language: php
php:
- 5.5
- 5.4
- hhvm
script: phpunit Test.php
deploy:
  provider: releases
  api_key:
    secure: MpcHIrcQ6mPDFBJ/fIc0BjMJonMJlIX5U5PRjLVwpyFwTf7+IeOTkOMDdGpNjj2j0zmEhKDSxROb6DUleUn4+qpEkJHtmfVAW5VX11vVEWDoEcMKwoOFPwRrsJc1uWtU9M2Ren+VelYVrRjUny56wTM9wClpxNZwES67HRLyY3/D9Cmdvwr9tw9PvZMhG9VCcCLkQMnq0YbknN79shiMuKuGzUOsMlox/W2BTCc65ZRm1dVXGCQDVKJmAOrvmEx0OGYSjM54jt/hKVfI5rDfoFmaYRdcqzuY5tK+vEugI4JzUAcCOsDnOFi4wQDmEcm3ADRqaIwbH56RCIdaEHhcEHalkl8pNDS1Bt3pmfLlbdc0uYVtTvSzwKoUa1V0yVY87Lts2ZDbtUG4IbUd8XJK+5vnaJAD0FWMRsNvunJIPa/TJVYScfBqwrZIqiEaSI6PiX/Cyz84wzkS65IFdPAl2RwqRV41oyKra5sKNlCpW8tnzHTcMVRVU+q3XAr9USS+M7DBLPrUDuvUgyWsrb8dZe+YurzISl0fCwwFaX7H0m28KdZjZBGU3T4y6fCY5nql3RVoSPqBYl/R48snvMvpDeZwOXz3kupbKHfU4MMl3VGDjF03kPvKmPxp299vbGiS3l7lWh1qO/9OYtyRZEohzXP1U1iAfUFuK/c8jnJgsTQ=
  file: releases
