language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php
deploy:
  provider: releases
  api_key: "82a7395c4ee4b6187da65a44053ae2d06951b599"
  file: "travis-broken.tgz"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
