language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php
deploy:
  provider: releases
  api_key: "bae6f6188af9f0cdfd3072b5c97f5b6f97c1be98"
  file: "travis-broken.tgz"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
